os: linux
dist: xenial
language: python
cache: pip
jobs:
  include:
    - python: "2.7"
      env: TOX_ENV=py27-dj17-sqlite
    - python: "2.7"
      env: TOX_ENV=py27-dj18-sqlite
    - python: "2.7"
      env: TOX_ENV=py27-dj19-sqlite
    - python: "2.7"
      env: TOX_ENV=py27-dj110-sqlite
    - python: "2.7"
      env: TOX_ENV=py27-dj111-sqlite
    - python: "3.5"
      env: TOX_ENV=py35-dj18-sqlite
    - python: "3.5"
      env: TOX_ENV=py35-dj19-sqlite
    - python: "3.5"
      env: TOX_ENV=py35-dj110-sqlite
    - python: "3.5"
      env: TOX_ENV=py35-dj111-sqlite
    - python: "3.5"
      env: TOX_ENV=py35-dj20-sqlite
    - python: "3.5"
      env: TOX_ENV=py35-dj21-sqlite
    # - python: "3.5"
    #   env: TOX_ENV=py35-dj22-sqlite
    - python: "3.6"
      env: TOX_ENV=py36-dj111-sqlite
    - python: "3.6"
      env: TOX_ENV=py36-dj20-sqlite
    - python: "3.6"
      env: TOX_ENV=py36-dj21-sqlite
    - python: "3.6"
      env: TOX_ENV=py36-dj22-sqlite
    - python: "3.6"
      env: TOX_ENV=py36-dj30-sqlite
    - python: "3.6"
      env: TOX_ENV=py36-dj31-sqlite
    - python: "3.6"
      env: TOX_ENV=py36-djmaster-sqlite
    - python: "3.7"
      env: TOX_ENV=py37-dj20-sqlite
    - python: "3.7"
      env: TOX_ENV=py37-dj21-sqlite
    - python: "3.7"
      env: TOX_ENV=py37-dj22-sqlite
    - python: "3.7"
      env: TOX_ENV=py37-dj30-sqlite
    - python: "3.7"
      env: TOX_ENV=py37-dj31-sqlite
    - python: "3.7"
      env: TOX_ENV=py37-djmaster-sqlite
    - python: "3.8"
      env: TOX_ENV=py38-dj22-sqlite
    - python: "3.8"
      env: TOX_ENV=py38-dj30-sqlite
     python: "3.8"
      env: TOX_ENV=py38-dj31-sqlite
    - python: "3.8"
      env: TOX_ENV=py38-djmaster-sqlite
  allow_failures:
    - env: TOX_ENV=py36-djmaster-sqlite
    - env: TOX_ENV=py37-djmaster-sqlite
    - env: TOX_ENV=py38-djmaster-sqlite
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
